extensions:
  health_check:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      http:  
      grpc:

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30
    
  batch:
    
  attributes:
    actions:
      - key: book.environment
        value: "development - set in the otel-collector-config.yml" 
        action: insert

exporters:
  debug:
  otlp/jaeger:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true

service:
#  telemetry: // use this setting to get the collector to produce logs for debugging collector issues
#    logs:
#      level: debug
  pipelines:
    traces:
      receivers:
        - otlp
      processors: [memory_limiter, attributes, batch]
      exporters:
        - debug
        - otlp/jaeger
    metrics:
      receivers:
        - otlp
      processors: [memory_limiter, batch]
      exporters:
        - debug
        - prometheus
    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki, debug]

  extensions:
    - health_check
    - zpages